--liquibase formatted sql

--changeset kalinin:001-create-product-table

CREATE TABLE product
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(50) NOT NULL,
    description  TEXT,
    product_type VARCHAR NOT NULL
);